### PR TITLE
Add symmetry span task

### PR DESCRIPTION
**Pull request by mingyus**

### CODE REVIEW

**Comment by szorowi1** [comment]
Hi Mingyu and Persis, 

I've started reviewing the code and I just wanted to quickly say: all of this looks fantastic! Thank you both for your hard work in putting all of this together. 

I'll begin working through the code in full detail later today and get back to you with a code review ASAP!

Best,
Sam

**Comment by szorowi1** [comment]
Hi @mingyus and Persis,

I've had a chance to work through the code -- this all looks great! Before merging the PR, I have three small suggestions and one clarification question:

**Suggestions** 

1. Would it be possible to upgrade the jspsych library from v6.0.4 to [v6.3.1](https://github.com/jspsych/jsPsych/releases)? If this breaks any dependencies, feel free to ignore.
2. Would it be possible to allow for forwards/backwards navigation in a section of instructions? For example, to allow participants to move forwards/backwards through the pages in the `instructions`, `instructions2`, etc. sections?
3. Would it be possible to make any necessary images (e.g. during the instructions, task, etc.) be [preloaded](https://www.jspsych.org/overview/media-preloading) during the experiment initialization? (This helps prevent media errors during online experiments.)

**Questions**

1. To confirm, is there a reason why participants have to click on the symmetry grid image to advance to the symmetry judgments? Is that how the Engle lab has their experiment? Is there any reason to not add the symmetry judgment buttons (i.e. "is this symmetrical?" yes, no) on the same page as the image itself?

Otherwise, everything looks great. Thank you both again for your hard work in putting this together and for this incredibly helpful resource for the lab!

Best,
Sam

**Comment by mingyus** [comment]
Hi Sam,

Thanks so much for reviewing the code! Great suggestions and questions!

> 1. Would it be possible to upgrade the jspsych library from v6.0.4 to [v6.3.1](https://github.com/jspsych/jsPsych/releases)? If this breaks any dependencies, feel free to ignore.
> 2. Would it be possible to allow for forwards/backwards navigation in a section of instructions? For example, to allow participants to move forwards/backwards through the pages in the `instructions`, `instructions2`, etc. sections?
> 3. Would it be possible to make any necessary images (e.g. during the instructions, task, etc.) be [preloaded](https://www.jspsych.org/overview/media-preloading) during the experiment initialization? (This helps prevent media errors during online experiments.)

Yes to all three of them! Will make these changes!

> 1. To confirm, is there a reason why participants have to click on the symmetry grid image to advance to the symmetry judgments? Is that how the Engle lab has their experiment? Is there any reason to not add the symmetry judgment buttons (i.e. "is this symmetrical?" yes, no) on the same page as the image itself?

Yes this is how the Engle lab has their experiment. The [mahiluthra version](https://github.com/mahiluthra/working_memory_tests) does the alternative way that you suggested (showing the symmetry images and judgement buttons on the same page). I tried both versions myself, and felt the former was a lot harder than the latter and more working-memory demanding. In the spirit of trying to follow the Engle lab version as close as possible (given they have tested the experiments extensively), I went with the former. But it's easy to bring back the other version and make it an option for the experimenter to decide which one to use. Would that be helpful?

Best,
Mingyu

**Comment by mingyus** [comment]
Hi @szorowi1 ,

I updated the code based your suggestions (upgraded jspsych lib, allowing backwards in instructions, and preloading images). I also added the option of doing the symmetry span task in one page (the default setting is still two-page, but can be changed to one-page by setting `symmetry_onepage = true`).

Let me know if you have more thoughts & comments!

Best,
Mingyu

**Comment by szorowi1** [comment]
Hi @mingyus,

This all looks fantastic! Thanks for addressing jspsych version and instructions navigations solutions. And I think your solution for one vs. two pages for the symmetry span makes perfect sense. 

I'll also ahead and approve the PR. Thank you and Persis again for this awesome contribution!

Best,
Sam

**Review by szorowi1 — APPROVED** [review]

**Pull request merged**
