### PR TITLE
Demographics #13

### PR DESCRIPTION
**Pull request by szorowi1**
Addressing issue #13. Small updates to the default demographics form:

- Adding self-report educational attainment
- Removing English language proficiency items

### CODE REVIEW

**Review by danielbrianbennett — APPROVED** [review]
Very minor feedback - education levels are listed as 'Associate degree', 'Bachelor degree', and 'Master degree'. I think these are more commonly (e.g., in the inces.ed.gov page) termed   "Associate's degree", "Bachelor's degree" and "Master's degree"

**Comment by szorowi1** [comment]
Yes, fully agreed! The degrees as presented to participants include the apostrophes but the internal variables exclude them. For example:

```html
<label><input type="radio" ... value="Bachelor degree">Bachelor's degree</label>
```

This was done mostly arbitrarily -- I try to avoid punctuation in variables, but there's no reason why I should do this. Would you prefer consistency in internal value and presentation?

**Comment by danielbrianbennett** [comment]
Oh, duh -- sorry, didn't read closely enough. Makes sense to me to exclude the apostrophe from internal variables.

**Comment by szorowi1** [comment]
Great, will commit and consider this resolved. Thanks for the prompt review!

**Pull request merged**
